spring:
  application:
    name: banking_service

  datasource:
    url: jdbc:postgresql://localhost:5435/banking_spring
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true



