spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  application:
    name: banking_service

  datasource:
    url: jdbc:postgresql://localhost:5435/banking_spring
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: yian.choi05@gmail.com
    password: guwcsrjgggccnppu
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true



